### PR TITLE
Cheat sheets and articles for databases and redis added.

### PR DESCRIPTION
**Pull request by theonlykingpin**

### CODE REVIEW

**Review by lnxpy — APPROVED** [review]
That's brilliant. Much appreciate your love Reza jan. Thanks.

**Comment by theonlykingpin** [comment]
Thanks Dear Sadra.

**Review by bobycloud — APPROVED** [review]
Wonderful, and many, many thanks for your participation in this.

**Comment by theonlykingpin** [comment]
Thanks you dear Mr Babazadeh. I appreciate.

**Pull request merged**
