### PR TITLE
add some video courses for python section

### PR DESCRIPTION
**Pull request by shahriaarrr**
add some video courses for python section((biggeners level and Intermediate level))

### CODE REVIEW

**Comment by bobycloud** [comment]
Hi, Thanks for your contribution dear @shahriaarrr 
Please follow the convention in this repository, for example: Python Beginner Tutorial((NeuralNine)) should be changed to Python Beginner Tutorial by NeuralNine

Please change and commit again so we can merge

Thank you

**Comment by bobycloud** [comment]
Hi, Thanks for your contribution dear @shahriaarrr 
Please follow the convention in this repository, for example: Python Beginner Tutorial((NeuralNine)) should be changed to Python Beginner Tutorial by NeuralNine

Please change and commit again so we can merge

Thank you

**Comment by shahriaarrr** [comment]
Hello @bobycloud .
The names of the course instructors were corrected according to what you said❤️
If there are more cases to correct, be sure to tell me to correct immediately

**Review by lnxpy — APPROVED** [review]
That LGTM. Thanks for your contribution. <3 :)

**Pull request merged**
