### PR TITLE
Podcasts and International Conferences Sections Created

### PR DESCRIPTION
**Pull request by lnxpy**

### CODE REVIEW

**Comment by bobycloud** [comment]
Great, thanks for your help dear Sadra, What's your opinion to make a new repository for podcasts and developer conferences and stuff like that?

**Comment by lnxpy** [comment]
LGTM. :))

**Comment by bobycloud** [comment]
Yea, this is a great idea and I love it. But let me think about it. I'm not sure whether to make a new repo or keep these resources in this repo. keep the issue open until we consider a good way to implement it. any idea would be welcoming.

**Comment by bobycloud** [comment]
Do we have lots of resources to make a new repo and fill it dear @lnxpy?

**Comment by lnxpy** [comment]
This PR will be approved on [djangoex/awesome-python-news](https://github.com/DjangoEx/awesome-python-news).

**Pull request closed without merging**
