### PR TITLE
 Add a few changes to the link structures

### PR DESCRIPTION
**Pull request by amirilf**
Add a new reference & fix a small bug (:

### CODE REVIEW

**Review by lnxpy — CHANGES_REQUESTED** [review]
It sounds nice but I think most libraries/frameworks notice their codebases and where all developments occur on their projects. (Like a GitHub repository, self-hosted Gitea, etc)

Thank you for your lovely contribution Amir jan. :)

**Comment by amirilf** [comment]
Hi dear, u r right but I think it becomes much more interesting & useful to include source code of the projects so that visitors can instantly reach the sources on GitHub & this can be performed for all items of this repository that have a source on GitHub (:

**Comment by amirilf** [comment]
@lnxpy @bobycloud 
What do you think about this?

**Review by lnxpy — APPROVED** [review]
It looks good to me Amir jan. Thanks mate. :))

**Review by bobycloud — APPROVED** [review]

**Comment by bobycloud** [comment]
Great, Thank you for your contribution dear @amirilf

**Pull request merged**
