### PR TITLE
Propose IoT for advanced topics 

### PR DESCRIPTION
**Pull request by malekzahedi**

### CODE REVIEW

**Review by lnxpy — CHANGES_REQUESTED** [review]
Thank you Mohammad jan. Much appreciate your love. :))
Would you please add the "IoT" title to the table of content section?!
Thoughts on having some GPIO references in this section?!

**Comment by malekzahedi** [comment]
You're welcome Sadra,
I added IoT to table of contents.
I don't have much experience in GPIO, so I can't decide it.

**Comment by lnxpy** [comment]
You're good. Thanks for updating the table. I may add it.

**Comment by malekzahedi** [comment]
I think we need embedded systems topic, then GPIO would go under it, not under IoT. Your thoughts?

**Review by bobycloud — APPROVED** [review]
Great, Thanks, Keep up the good work!

**Pull request merged**
